# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b982f11fb6e89c8bffa35166c7bf02b1e9c074a98b847a33de7cb7fac8204e166e7acfc0ef72c3293e9462aa6a697f01aec109741f1098bede49924544f2a1e9

test:
  secret_key_base: 552162a2f61bf9038ebbd7947e2b618c7545d21c45d0484fc4d480f80b2c4c3478b75ffbf35a4c8b6f2a84b1852270910dd53cbd50ee529453d220f2fca107d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
